// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyjBEgyHgAhzYw0BC5ahrHqL6aGzwhMJA',
    appId: '1:816692589903:web:2418dbfb19b98365b0c13a',
    messagingSenderId: '816692589903',
    projectId: 'bgm-elearningplatform-2bb9e',
    authDomain: 'bgm-elearningplatform-2bb9e.firebaseapp.com',
    storageBucket: 'bgm-elearningplatform-2bb9e.firebasestorage.app',
    measurementId: 'G-P1648DY9Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHbJa7BGNlOjkWiO24jyw8VRtPVflA9o',
    appId: '1:816692589903:android:6d82ad0b1da3d5e3b0c13a',
    messagingSenderId: '816692589903',
    projectId: 'bgm-elearningplatform-2bb9e',
    storageBucket: 'bgm-elearningplatform-2bb9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpf1_Ycs7cM9JXRDwNQm8LgUDIH1lwfl0',
    appId: '1:816692589903:ios:57c8e0c607e18154b0c13a',
    messagingSenderId: '816692589903',
    projectId: 'bgm-elearningplatform-2bb9e',
    storageBucket: 'bgm-elearningplatform-2bb9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpf1_Ycs7cM9JXRDwNQm8LgUDIH1lwfl0',
    appId: '1:816692589903:ios:57c8e0c607e18154b0c13a',
    messagingSenderId: '816692589903',
    projectId: 'bgm-elearningplatform-2bb9e',
    storageBucket: 'bgm-elearningplatform-2bb9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyjBEgyHgAhzYw0BC5ahrHqL6aGzwhMJA',
    appId: '1:816692589903:web:faddb6dfd7b9b234b0c13a',
    messagingSenderId: '816692589903',
    projectId: 'bgm-elearningplatform-2bb9e',
    authDomain: 'bgm-elearningplatform-2bb9e.firebaseapp.com',
    storageBucket: 'bgm-elearningplatform-2bb9e.firebasestorage.app',
    measurementId: 'G-ZZEJSNM1MR',
  );

}